# PHP Obfuscator Configuration

# General behavior settings
silent: false                    # Suppress informational messages
abort_on_error: true             # Stop processing on the first error
debug_mode: false                # Enable verbose debug logging
parser_mode: "PREFER_PHP7"       # PHP Parser version preference (PREFER_PHP7, PREFER_PHP8, etc.)

# Obfuscation options
obfuscation:
  # String obfuscation settings
  strings:
    enabled: true                # Enable string literal obfuscation
    technique: "base64"          # Options: "base64", "rot13", "xor"
    # Optional: Define XOR key if technique is XOR
    # xor_key: "YourSecretKey"

  # Name scrambling settings
  scrambling:
    mode: "identifier"           # Options: "identifier", "hexa", "numeric"
    length: 5                    # Target length for scrambled names

  # Comment handling
  comments:
    strip: false                 # Remove comments from the PHP code

  # Which specific name types to scramble (add more as needed: constants, properties, methods, etc.)
  variables: { scramble: false } # Obfuscate variable names ($var)
  functions: { scramble: false } # Obfuscate function names (myFunc())
  classes:   { scramble: false } # Obfuscate class/interface/trait names (MyClass)
  # Add more specific type toggles here (e.g., properties, methods, constants) if needed

  # Control flow obfuscation
  control_flow:
    enabled: true                # Wrap blocks in if(true){} statements
    max_nesting_depth: 2         # Maximum depth for nested control flow obfuscation
    random_conditions: true      # Use random conditions (true/1==1/5>2) for better obfuscation
    add_dead_branches: false     # Add bogus else{} branches to if statements

  # Advanced loop obfuscation (sentinel variables, etc.)
  advanced_loops:
    enabled: false

  # Array access obfuscation (experimental)
  array_access:
    enabled: true                # Transform array access into function calls

  # Arithmetic expression obfuscation (experimental)
  # arithmetic_expressions:
  #   enabled: false
  #   complexity_level: 1          # Controls complexity (e.g., 1-3)
  #   transformation_rate: 50      # Percentage of eligible expressions to transform (0-100)

  # Dead code injection
  dead_code:
    enabled: false               # Insert dead code that never executes
    injection_rate: 30           # Percentage chance to inject at each opportunity (0-100)

  # Junk code insertion
  junk_code:
    enabled: false               # Insert junk code like unused variables and no-op calculations
    injection_rate: 30           # Percentage chance to inject at each opportunity (0-100)
    max_injection_depth: 3       # Maximum depth for code injection to prevent excessive nesting

  # Statement shuffling
  statement_shuffling:
    enabled: true                # Shuffle independent statements within blocks
    min_chunk_size: 2            # Minimum number of statements to consider for shuffling
    chunk_mode: "fixed"          # "fixed" or "ratio"
    chunk_ratio: 20              # Percentage of statements to include in a chunk

  # Exclusions/Ignores for scrambling
  ignore:
    functions: []                # List of function names to ignore during scrambling
    variables: []                # List of variable names (without $) to ignore
    classes: []                  # List of class/interface/trait names to ignore
    # Add more ignore lists as needed (properties, methods, constants etc.)

# File processing options (remain top-level)
skip: ["vendor/*", "*.git*", "*.svn*", "*.bak"] # Glob patterns for files/dirs to skip entirely
keep: []                                        # Glob patterns for files/dirs to copy without obfuscating
obfuscate_php_extensions: ["php", "php5", "phtml"] # File extensions to treat as PHP
follow_symlinks: false                          # Follow symbolic links instead of copying them
target_directory: ""                            # Output directory (set internally via CLI flag)

# --- LEGACY KEYS REMOVED ---
# (All flat keys like strip_comments, obfuscate_string_literal, etc., are gone)
  