name: Release Binaries

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        include:
          - goos: windows
            asset_suffix: .exe
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: ./cmd/go-php-obfuscator  # Path to your Go source files
          binary_name: "phpmixer"
          asset_name: phpmixer-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.asset_suffix }}
          extra_files: LICENSE README.md
